cicd: Dockerfile update

diff --git a/.github/workflows/cicd-docker-prod.yml b/.github/workflows/cicd-docker-prod.yml
--- a/.github/workflows/cicd-docker-prod.yml
+++ b/.github/workflows/cicd-docker-prod.yml
@@ -36,6 +36,12 @@ jobs:
       - name: 🐵 Log in to GHCR
         run: echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
 
+      - name: 🔍 Check files before docker build
+        run: |
+          pwd
+          ls -al
+          cat Dockerfile || echo "❌ Dockerfile not found"
+
       - name: 🐵 Build Docker Image
         run: |
           docker build -f ./Dockerfile -t ${{ env.REGISTRY }}/${{ env.REPO }}:${{ github.sha }} .
